import json
import logging

from .base import ExportPlugin

logger = logging.getLogger(__name__)


class MitreNavPlugin(ExportPlugin):
    name = "mitre_nav"
    required_env = []

    async def export(self, pool) -> dict:
        async with pool.acquire() as conn:
            skill_rows = await conn.fetch("""
                SELECT mitre_techniques, confidence_score, usage_count
                FROM soc_skills
                WHERE mitre_techniques IS NOT NULL AND array_length(mitre_techniques, 1) > 0
            """)
            alert_rows = await conn.fetch("""
                SELECT raw_alert->>'mitre_techniques' AS techniques, confidence
                FROM ai_analysis
                WHERE raw_alert ? 'mitre_techniques'
                  AND raw_alert->>'mitre_techniques' IS NOT NULL
            """)

        scores: dict[str, dict] = {}

        for row in skill_rows:
            for tech in (row["mitre_techniques"] or []):
                tid = tech.strip().upper()
                if not tid:
                    continue
                entry = scores.setdefault(tid, {"score_sum": 0.0, "count": 0})
                entry["score_sum"] += float(row["confidence_score"] or 0) * 100
                entry["count"]     += max(1, int(row["usage_count"] or 1))

        for row in alert_rows:
            try:
                techs = json.loads(row["techniques"] or "[]")
            except (json.JSONDecodeError, TypeError):
                continue
            for tech in techs:
                tid = tech.strip().upper()
                if not tid:
                    continue
                entry = scores.setdefault(tid, {"score_sum": 0.0, "count": 0})
                entry["score_sum"] += float(row["confidence"] or 0) * 100
                entry["count"]     += 1

        techniques = []
        for tid, data in scores.items():
            avg_score = int(data["score_sum"] / max(data["count"], 1))
            techniques.append({
                "techniqueID":       tid,
                "score":             avg_score,
                "color":             "",
                "comment":           f"Seen {data['count']}x | avg score {avg_score}",
                "enabled":           True,
                "metadata":          [],
                "links":             [],
                "showSubtechniques": False,
            })

        layer = {
            "name":        "NexusSoc Threat Detections",
            "versions":    {"attack": "14", "navigator": "4.9.1", "layer": "4.5"},
            "domain":      "enterprise-attack",
            "description": f"Auto-generated by NexusSoc — {len(techniques)} techniques detected",
            "filters":     {"platforms": ["Windows", "Linux", "macOS", "Network", "Cloud"]},
            "sorting":     3,
            "layout":      {"layout": "side", "aggregateFunction": "average", "showID": True, "showName": True},
            "hideDisabled": False,
            "techniques":  techniques,
            "gradient":    {"colors": ["#ff6666ff", "#ffe766ff", "#8ec843ff"], "minValue": 0, "maxValue": 100},
            "legendItems": [],
            "metadata":    [],
            "showTacticRowBackground":       False,
            "tacticRowBackground":           "#dddddd",
            "selectTechniquesAcrossTactics": True,
            "selectSubtechniquesWithParent": False,
        }

        return {
            "content":    json.dumps(layer, indent=2),
            "media_type": "application/json",
            "filename":   "nexussoc-navigator.json",
        }
